Add function to look up CCC directly from u32
yeslogic/unicode-canonical-combining-class pull request #4
Opened 2022-07-13 19:04 UTC by theodore-s-beers

This should be pretty self-explanatory—though whether you want it in the library is a different question.

The original function already does what it's supposed to (return `NotReordered`) if you pass it an invalid `char` generated from a `u32` with the unsafe method. This would simply cut out the middleman. I've found myself running `char::from_u32_unchecked` just to get a `char` to fetch the CCC, and that seems silly, given that the lookup function immediately casts it back.

Anyway, I added the new function, gave it a bit of documentation, and duplicated the existing tests. I haven't done anything with the readme or the module docs. Thanks!

2022-07-13 23:17 UTC, wezm requested changes
Thanks for this. I think the original intention behind using `char` what that way you know it's a valid Unicode code point but given how the lookup works I suppose this distinction isn't especially important.

2022-07-13 23:17 UTC, wezm commented on src/canonical_combining_class.rs
> +    }
Since this is the same code as `get_canonical_combining_class` could you make that call this function instead of having it's own copy of the code.

2022-07-14 00:07 UTC, theodore-s-beers commented on src/canonical_combining_class.rs
> +    }
Ok, I just pushed a change to that effect (assuming I understood correctly).

2022-07-14 00:21 UTC, theodore-s-beers commented
> Thanks for this. I think the original intention behind using `char` what that way you know it's a valid Unicode code point but given how the lookup works I suppose this distinction isn't especially important.

Yeah, and the tables cover the whole Unicode range, if I'm not mistaken. No foreseeable `char` could ever hit that `else` block. Come to think of it, I'm not sure I've ever triggered it, myself. I was thinking that the conformance tests for the Unicode Collation Algorithm include some screwy values—and they do—but I guess they never go above 10FFFF.

I still think it's definitely correct to return `NotReordered` for an invalid char value, just as is done for unassigned code points.

The real benefit of the new function, for me, is avoiding casts back to `char` when I'm already working with `u32` values.

2022-07-14 01:25 UTC, merged